### ISSUE TITLE
Document mutation-based logic error

### ISSUE THREAD

**Issue by apasel422** [contain-rs/interval-heap#9]
Add this to the `IntervalHeap` doc:

> It is a logic error for an item to be modified in such a way that the item's ordering relative to any other item, as determined by the heap's comparator, changes while it is in the heap. This is normally only possible through Cell, RefCell, global state, I/O, or unsafe code.

**Comment by Gankra** [comment]
I kinda assumed that that goes without saying but sure, why not.

**Comment by apasel422** [comment]
We added this disclaimer to the collections in `std`: rust-lang/rust#23342.
